---
## 網站資訊

baseURL       : https://bwaycer.github.io/blog/
languageCode  : zh
title         : 第二方案

# 多國語系製作相對複雜（上下頁），建議不使用
languages:
    zh:
        title: 第二方案
    en:
        title: B.Way


## 主題
# https://github.com/jpescador/hugo-future-imperfect


## 開發設定值

newContentEditor   : vim
metaDataFormat     : yaml
disableLiveReload  : false
verbose            : true


## 開發設定值 - 資料結構

archetypeDir  : archetypes
contentDir    : content
dataDir       : data
layoutDir     : layouts
staticDir     : static
themesDir     : themes
publishDir    : public


## 開發設定值 - 生成文檔

defaultContentLanguage                : zh
defaultContentLanguageInSubdir        : false
enableMissingTranslationPlaceholders  : false

relativeURLs : true


## 主題預設值

preserveTaxonomyNames: true
paginate: 3

params:
    isDeveloper  : true

    # `meta` 元素標籤的描述，當內容頁無值時使用的預設描述
    description          : 希望我的旅途，能引領你翱翔，或許默默贊同，或許熱烈迴響。

    # 是否顯示預估閱讀時間（`ReadingTime` 由 Hogo 內建，好特別的功能）
    includeReadingTime   : true


# 設定導覽行的項目
# 其允許在文字前添加個 font awesome 圖示字型

menu:

    main:

        - name       : 關於我
          identifier : fa fa-user-o
          url        : https://bwaycer.github.io/about
          weight     : 1

        - name       : 標籤
          identifier : fa fa-tags
          url        : /categories
          weight     : 2
...
